version: '3'

services:

  glances:
    image: vimagick/glances
    volumes:
      - ./data:/etc/glances
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - GLANCES_OPT=-w
    ports:
      - 5280:61208
    pid: host
    restart: always